"""Python entry points for notebook-based MGE organoid analysis."""

from .cell_cycle import (
    CCDIFFERENCE_KEY,
    CELL_CYCLE_GENE_SOURCE,
    G2M_PHASE_GENES,
    S_PHASE_GENES,
    CellCycleGeneSelection,
    cell_cycle_gene_summary,
    cell_cycle_gene_table,
    cell_cycle_score_summary,
    score_cell_cycle_and_ccdifference,
    select_cell_cycle_genes,
)
from .converter import SeuratToAnnDataConverter
from .data_sources import (
    DatasetLoadResult,
    Notebook00SourceConfig,
    cellbender_output_table,
    expected_cellbender_output_h5,
    load_dataset_result,
    sample_table,
    source_availability_table,
    summarize_source_availability,
)
from .loader import cached_h5ad_path, load_cached_anndata, load_cached_anndatas, missing_cached_h5ads
from .notebook00_plots import PlotConfig
from .notebook00_workflow import (
    ManualECCheckpointPaths,
    ManualECCheckpointSettings,
    ManualECFilterSettings,
    save_manual_ec_checkpoints,
    validate_manual_ec_checkpoint_pair,
)
from .notebook01_workflow import (
    NOTEBOOK01_BASE_OPERATION_ORDER,
    NOTEBOOK01_DEFAULT_QC_REGRESS_KEYS,
    NOTEBOOK01_DEFAULT_REGRESS_KEYS,
    NOTEBOOK01_REGRESSION_BRANCHES,
    Notebook01EmbeddingSettings,
    Notebook01HVGSettings,
    Notebook01InputPaths,
    Notebook01InputSettings,
    Notebook01OutputPaths,
    Notebook01RegressionVariant,
    Notebook01RunSettings,
    branch_operation_order,
    default_regression_variants,
    embedding_table,
    infer_run_sample_ids,
    planned_analysis_table,
    parse_csv,
    run_hvg_selection,
    run_regression_embedding_branch,
    save_pca_variance_plot,
    save_umap_branch_comparison_plot,
    save_umap_plot,
    umap_comparison_payload,
    validate_notebook01_input,
)
from .paths import DEFAULT_PROJECT_ROOT, resolve_project_root
from .studies import StudySpec, default_studies
from .validation import AnnDataReport, validate_anndata, validate_source_paths

__all__ = [
    "AnnDataReport",
    "CCDIFFERENCE_KEY",
    "CELL_CYCLE_GENE_SOURCE",
    "CellCycleGeneSelection",
    "DEFAULT_PROJECT_ROOT",
    "DatasetLoadResult",
    "G2M_PHASE_GENES",
    "ManualECCheckpointPaths",
    "ManualECCheckpointSettings",
    "ManualECFilterSettings",
    "Notebook01InputPaths",
    "Notebook01InputSettings",
    "Notebook01OutputPaths",
    "Notebook01RegressionVariant",
    "Notebook01RunSettings",
    "NOTEBOOK01_BASE_OPERATION_ORDER",
    "NOTEBOOK01_DEFAULT_QC_REGRESS_KEYS",
    "NOTEBOOK01_DEFAULT_REGRESS_KEYS",
    "NOTEBOOK01_REGRESSION_BRANCHES",
    "Notebook01EmbeddingSettings",
    "Notebook01HVGSettings",
    "Notebook00SourceConfig",
    "PlotConfig",
    "SeuratToAnnDataConverter",
    "S_PHASE_GENES",
    "StudySpec",
    "cached_h5ad_path",
    "cell_cycle_gene_summary",
    "cell_cycle_gene_table",
    "cell_cycle_score_summary",
    "cellbender_output_table",
    "branch_operation_order",
    "default_studies",
    "default_regression_variants",
    "embedding_table",
    "expected_cellbender_output_h5",
    "infer_run_sample_ids",
    "load_dataset_result",
    "load_cached_anndata",
    "load_cached_anndatas",
    "missing_cached_h5ads",
    "planned_analysis_table",
    "parse_csv",
    "resolve_project_root",
    "run_hvg_selection",
    "run_regression_embedding_branch",
    "sample_table",
    "score_cell_cycle_and_ccdifference",
    "select_cell_cycle_genes",
    "save_pca_variance_plot",
    "save_umap_branch_comparison_plot",
    "save_manual_ec_checkpoints",
    "save_umap_plot",
    "source_availability_table",
    "summarize_source_availability",
    "umap_comparison_payload",
    "validate_anndata",
    "validate_manual_ec_checkpoint_pair",
    "validate_notebook01_input",
    "validate_source_paths",
]
