#!/usr/bin/env python3
"""Export a stratified DIV30 Matrix Market bundle for the first URD run.

The expression matrix comes from the AnnData export of the DIV30 Seurat object:

    results/python_anndata/varela_div30_2f0j5mwk/matrix_counts.mtx

The lineage annotations come from the sidecar generated by
`map_div30_paper_cluster_annotations.py`. The default export is a stratified
pilot subset, not a rewrite of the original data. Set `--max-cells 0` to export
all mapped DIV30 cells.

This script imposes only input-bundle decisions:

    - which source count matrix and metadata sidecars are joined;
    - whether the run uses all cells or a stratified pilot subset;
    - which metadata label marks URD root candidates.

It does not normalize expression, choose variable genes, compute PCA/diffusion
maps, or run pseudotime. Those URD-specific parameters live in
scripts/14_div30_first_urd.R and are recorded by that script in
tables/div30_first_urd_parameters.tsv.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.io import mmread, mmwrite


DEFAULT_PROJECT_ROOT = Path("/nfs/turbo/umms-parent/mgeo_neuron_scrnaseq_projectfolder")
DEFAULT_RUN_LABEL = "div30_first_urd_paper_radial_glia_v1"
DEFAULT_MAX_CELLS = 30_000
DEFAULT_ROOT_LABEL = "Radial glia"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path(os.environ.get("PROJECT_ROOT", DEFAULT_PROJECT_ROOT)),
    )
    parser.add_argument("--run-label", default=os.environ.get("RUN_LABEL", DEFAULT_RUN_LABEL))
    parser.add_argument("--anndata-dir", type=Path, default=None)
    parser.add_argument("--paper-annotations", type=Path, default=None)
    parser.add_argument("--shi-obs", type=Path, default=None)
    parser.add_argument("--outdir", type=Path, default=None)
    parser.add_argument("--max-cells", type=int, default=int(os.environ.get("MAX_CELLS", DEFAULT_MAX_CELLS)))
    parser.add_argument("--seed", type=int, default=int(os.environ.get("SEED", "7")))
    parser.add_argument("--root-label", default=os.environ.get("ROOT_LABEL", DEFAULT_ROOT_LABEL))
    return parser.parse_args()


def default_paths(project_root: Path, run_label: str) -> dict[str, Path]:
    return {
        "anndata_dir": project_root / "results" / "python_anndata" / "varela_div30_2f0j5mwk",
        "paper_annotations": project_root
        / "results"
        / "div30_paper_cluster_annotations"
        / "div30_paper_cluster_annotations_v1"
        / "tables"
        / "div30_jia_scores_with_paper_cluster_annotations.tsv.gz",
        "shi_obs": project_root
        / "results"
        / "shi_reference_div30_seurat_label_transfer"
        / "shi_reference_div30_seurat_label_transfer_v1"
        / "tables"
        / "div30_shi_seurat_label_transfer_obs.tsv.gz",
        "outdir": project_root / "results" / "div30_first_urd" / run_label / "inputs",
    }


def read_single_column_tsv(path: Path, column_name: str) -> pd.Series:
    df = pd.read_csv(path, sep="\t")
    if column_name not in df.columns:
        raise ValueError(f"{path} does not contain column {column_name!r}")
    return df[column_name].astype(str)


def select_cells(metadata: pd.DataFrame, max_cells: int, seed: int) -> pd.DataFrame:
    """Return cells to export while preserving source matrix column order.

    If `max_cells` is positive and smaller than the available metadata, cells
    are sampled proportionally within `paper_cluster_annotation`. The exact
    exported cells are written to div30_first_urd_cell_metadata.tsv, so this
    sampling step is reproducible from the manifest and selected metadata.
    """

    if max_cells <= 0 or len(metadata) <= max_cells:
        out = metadata.copy()
        out["urd_sampling_status"] = "all_cells"
        return out

    rng = np.random.default_rng(seed)
    sampled_parts: list[pd.DataFrame] = []
    group_sizes = metadata["paper_cluster_annotation"].value_counts()
    allocation = (group_sizes / group_sizes.sum() * max_cells).round().astype(int)
    allocation = allocation.clip(lower=1, upper=group_sizes)

    while allocation.sum() > max_cells:
        candidates = allocation[allocation > 1].sort_values(ascending=False)
        allocation.loc[candidates.index[0]] -= 1
    while allocation.sum() < max_cells:
        candidates = (group_sizes - allocation).sort_values(ascending=False)
        candidates = candidates[candidates > 0]
        if candidates.empty:
            break
        allocation.loc[candidates.index[0]] += 1

    for label, n_cells in allocation.items():
        group = metadata[metadata["paper_cluster_annotation"] == label]
        chosen = rng.choice(group.index.to_numpy(), size=int(n_cells), replace=False)
        sampled_parts.append(group.loc[np.sort(chosen)])

    out = pd.concat(sampled_parts, axis=0).sort_values("matrix_col_index")
    out["urd_sampling_status"] = f"stratified_max_{max_cells}"
    return out


def main() -> None:
    args = parse_args()
    project_root = args.project_root.expanduser().resolve()
    paths = default_paths(project_root, args.run_label)
    anndata_dir = (args.anndata_dir or paths["anndata_dir"]).expanduser().resolve()
    paper_path = (args.paper_annotations or paths["paper_annotations"]).expanduser().resolve()
    shi_path = (args.shi_obs or paths["shi_obs"]).expanduser().resolve()
    outdir = (args.outdir or paths["outdir"]).expanduser().resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    counts_path = anndata_dir / "matrix_counts.mtx"
    barcodes_path = anndata_dir / "barcodes.tsv"
    features_path = anndata_dir / "features.tsv"
    umap_path = anndata_dir / "umap.tsv"
    for path in [counts_path, barcodes_path, features_path, umap_path, paper_path]:
        if not path.exists():
            raise FileNotFoundError(path)

    print(f"[Div30FirstURDExport] project_root={project_root}", flush=True)
    print(f"[Div30FirstURDExport] counts={counts_path}", flush=True)
    print(f"[Div30FirstURDExport] paper_annotations={paper_path}", flush=True)
    print(f"[Div30FirstURDExport] shi_obs={shi_path}", flush=True)
    print(f"[Div30FirstURDExport] outdir={outdir}", flush=True)

    barcodes = read_single_column_tsv(barcodes_path, "cell_id")
    features = read_single_column_tsv(features_path, "feature_id")
    paper = pd.read_csv(paper_path, sep="\t")
    umap = pd.read_csv(umap_path, sep="\t")
    metadata = paper.merge(umap, on="cell_id", how="inner", validate="one_to_one")
    if shi_path.exists():
        shi_cols = [
            "cell_id",
            "shi_seurat_full_predicted_shi_label",
            "shi_seurat_full_prediction_score",
            "shi_seurat_full_developmental_class",
            "shi_seurat_full_prediction_score_MGE",
            "shi_seurat_full_prediction_score_progenitor",
            "shi_seurat_full_expected_shi_week_numeric",
        ]
        shi = pd.read_csv(shi_path, sep="\t", usecols=lambda col: col in shi_cols)
        metadata = metadata.merge(shi, on="cell_id", how="left", validate="one_to_one")

    barcode_index = pd.Series(np.arange(len(barcodes)), index=barcodes.values)
    metadata["matrix_col_index"] = metadata["cell_id"].map(barcode_index)
    missing = int(metadata["matrix_col_index"].isna().sum())
    if missing:
        raise ValueError(f"{missing} annotated cells were absent from {barcodes_path}")
    metadata["matrix_col_index"] = metadata["matrix_col_index"].astype(int)

    selected = select_cells(metadata, args.max_cells, args.seed)
    # The R runner uses this boolean column directly. Keeping the root decision
    # in the exported metadata makes each root definition explicit and lets later
    # runs swap the root label without rewriting the source Seurat object.
    selected["urd_root_candidate"] = selected["paper_cluster_annotation"].astype(str) == args.root_label
    if not bool(selected["urd_root_candidate"].any()):
        raise ValueError(f"No cells matched root label {args.root_label!r}")

    print(f"[Div30FirstURDExport] selected_cells={len(selected)}", flush=True)
    print(selected["paper_cluster_annotation"].value_counts().sort_index().to_string(), flush=True)

    print("[Div30FirstURDExport] reading Matrix Market counts", flush=True)
    counts = mmread(counts_path).tocsc()
    if counts.shape != (len(features), len(barcodes)):
        raise ValueError(
            f"Counts shape {counts.shape} does not match features/barcodes "
            f"({len(features)}, {len(barcodes)})"
        )

    selected_counts = counts[:, selected["matrix_col_index"].to_numpy()].tocoo()
    selected_counts_path = outdir / "div30_first_urd_counts.mtx"
    selected_features_path = outdir / "div30_first_urd_features.tsv"
    selected_metadata_path = outdir / "div30_first_urd_cell_metadata.tsv"
    selected_barcodes_path = outdir / "div30_first_urd_barcodes.tsv"
    manifest_path = outdir / "div30_first_urd_input_manifest.tsv"

    print(f"[Div30FirstURDExport] writing {selected_counts_path}", flush=True)
    mmwrite(selected_counts_path, selected_counts)
    pd.DataFrame({"feature_id": features}).to_csv(selected_features_path, sep="\t", index=False)
    pd.DataFrame({"cell_id": selected["cell_id"].to_numpy()}).to_csv(selected_barcodes_path, sep="\t", index=False)

    metadata_cols = [
        "cell_id",
        "obs_name",
        "orig.ident",
        "seurat_clusters",
        "RNA_snn_res.0.2",
        "paper_cluster_annotation",
        "paper_developmental_stage",
        "paper_developmental_order",
        "jia_score_IPC",
        "jia_score_RGC1",
        "jia_score_RGC2",
        "UMAP_1",
        "UMAP_2",
        "urd_root_candidate",
        "urd_sampling_status",
        "matrix_col_index",
        "shi_seurat_full_predicted_shi_label",
        "shi_seurat_full_prediction_score",
        "shi_seurat_full_developmental_class",
        "shi_seurat_full_prediction_score_MGE",
        "shi_seurat_full_prediction_score_progenitor",
        "shi_seurat_full_expected_shi_week_numeric",
    ]
    selected[[col for col in metadata_cols if col in selected.columns]].to_csv(
        selected_metadata_path,
        sep="\t",
        index=False,
    )

    manifest = pd.DataFrame(
        [
            {"key": "source_counts", "value": str(counts_path)},
            {"key": "source_barcodes", "value": str(barcodes_path)},
            {"key": "source_features", "value": str(features_path)},
            {"key": "source_umap", "value": str(umap_path)},
            {"key": "source_paper_annotations", "value": str(paper_path)},
            {"key": "source_shi_obs", "value": str(shi_path)},
            {"key": "matrix_orientation", "value": "features_by_cells"},
            {"key": "metadata_join_key", "value": "cell_id"},
            {"key": "cell_selection_logic", "value": "all_cells_if_max_cells_le_0_else_stratified_by_paper_cluster_annotation"},
            {"key": "root_label", "value": args.root_label},
            {"key": "root_candidate_logic", "value": "paper_cluster_annotation == root_label"},
            {"key": "max_cells", "value": str(args.max_cells)},
            {"key": "seed", "value": str(args.seed)},
            {"key": "n_selected_cells", "value": str(len(selected))},
            {"key": "n_root_cells", "value": str(int(selected["urd_root_candidate"].sum()))},
            {"key": "counts_mtx", "value": str(selected_counts_path)},
            {"key": "features_tsv", "value": str(selected_features_path)},
            {"key": "barcodes_tsv", "value": str(selected_barcodes_path)},
            {"key": "cell_metadata_tsv", "value": str(selected_metadata_path)},
        ]
    )
    manifest.to_csv(manifest_path, sep="\t", index=False)
    print(f"[Div30FirstURDExport] complete: {outdir}", flush=True)


if __name__ == "__main__":
    main()
