name: imaris-careamics
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - h5py
  - tifffile
  - imageio
  - imageio-ffmpeg
  - matplotlib
  - pytorch>=2.2
  - pytorch-cuda=12.1
  - pip:
      - careamics==0.3.2
      - hdf5plugin
